version: "3"

services:
  helium:
    image: helium
    container_name: helium
    restart: always
    depends_on:
      - minio
    environment:
      helium_key: YOURKEYHERE
      helium_s3_bucket: helium
      helium_s3_host: http://minio:9000
      helium_s3_acc_key: minio
      helium_s3_sec_key: minio123
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"

  minio:
    image: minio/minio:RELEASE.2020-11-13T20-10-18Z
    volumes:
      - ./data:/data1
    ports:
      - "9000:9000"
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3